POST http://localhost:8085/auth/signup/
content-type: application/json

{
    "login": "D4SuCE_",
    "password": "123",
    "password_repeat": "123"
}

###

POST http://localhost:8085/auth/signin/

{
    "login": "D4SuCE_",
    "password": "123"
}

###

POST http://localhost:8085/api/v1/todo_list/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODQ1NjgyOTQsIm5pY2tuYW1lIjoiRDRTdUNFXyIsInN1YiI6Mn0.NzTYBCN_g6Jq5a1o_Dnc0CmmzLHrLvxJAtpZoEBrsEI
content-type: application/json

{
    "title": "first todo list D4SuCE_",
    "description": "firs test todo list"
}


###

DELETE http://localhost:8085/api/v1/todo_list/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2ODQ1NjgyOTQsIm5pY2tuYW1lIjoiRDRTdUNFXyIsInN1YiI6Mn0.NzTYBCN_g6Jq5a1o_Dnc0CmmzLHrLvxJAtpZoEBrsEI
content-type: application/json


###

PUT http://localhost:8085/api/v1/todo_list/10
Authorization: gvPQEohExMfHmgVhkaUTvrdWxJVbuDyCYqlsNayk
content-type: application/json

{
    "title": "TEST4",
    "description": "dasdsadd"
}

###


GET http://localhost:8085/api/v1/todo_list/
Authorization: gvPQEohExMfHmgVhkaUTvrdWxJVbuDyCYqlsNayk
content-type: application/json

###

GET http://localhost:8085/api/v1/todo_list/10
Authorization: gvPQEohExMfHmgVhkaUTvrdWxJVbuDyCYqlsNayk
content-type: application/json

###

POST http://localhost:8085/api/v1/todo_list/10/todo/
Authorization: gvPQEohExMfHmgVhkaUTvrdWxJVbuDyCYqlsNayk
content-type: application/json

{
    "title": "Cходить в qwerty"
}

###

DELETE http://localhost:8085/api/v1/todo_list/10/todo/3
Authorization: gvPQEohExMfHmgVhkaUTvrdWxJVbuDyCYqlsNayk
content-type: application/json
