definitions:
  models.User:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
info:
  contact: {}
paths:
  /auth/signup/:
    post:
      consumes:
      - application/json
      description: SignUp new user
      parameters:
      - description: Add account
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.User'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: SignUp new user
      tags:
      - auth
swagger: "2.0"
